# Generated by Django 4.2.1 on 2023-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('address_street', models.CharField(max_length=100, null=True)),
                ('address_number', models.IntegerField(null=True)),
                ('address_neighborhood', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
