# Generated by Django 4.2.1 on 2023-06-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('cars', '0006_alter_car_status'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('finishes_at', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('car_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('customer_RG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
