# Generated by Django 4.2.1 on 2023-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_brand_alter_car_chassis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
