# Generated by Django 4.2.1 on 2023-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
