# Generated by Django 4.2.1 on 2023-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='Available', max_length=20, null=True),
        ),
    ]
